export type Role = 'ADMIN' | 'PATIENT' | 'DOCTOR' | 'NURSE' | 'LAB_TECHNICIAN' | 'CASHIER'

export enum RoleEnum {
  ADMIN = 'ADMIN',
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  LAB_TECHNICIAN = 'LAB_TENCHNICIAN',
  CASHIER = 'CASHIER'
}
